title: Martin Hollingsworth | Thinking about tech, still nothing very useful...
description: Martin Hollingsworth's personal blog about software development, and the crazy things  that sometimes force their way into my head.
author: Martin Hollingsworth
email: martinh.reg@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mgholls.github.io" # the base hostname & protocol for your site
github_username: mgholls
linkedin_username: martin-hollingsworth # your LinkedIn username (optional)
twitter_username: mgholls # your Twitter username (optional)

# The 'header_pages' configuration specifies which pages should appear in the site's header navigation.
# Add the filenames of the pages you want to include in the header navigation here.
header_pages:
  - index.md
  - blog/index.html

# WARNING: 'future' is set to true to allow future-dated posts to be published.
# Review this setting before deploying to production or sharing your site widely.
future: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

# Permalink style
permalink: /blog/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
